server:
  servlet:
    context-path: /mini
  port: 2005

logging:
    level:
        com.github.valerie.wx.miniapp: debug
        org.springframework.web: info
        cn.binarywang.wx.miniapp: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 0824,Love
    url: jdbc:mysql://localhost:3306/clock?characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://47.102.210.132:2005/clock?characterEncoding=UTF-8&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  redis:
    database: 0
    password: 0824,Love
    port: 6379
    host: localhost
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1000
      shutdown-timeout: 3000

wx:
  miniapp:
    configs:
      - appid: wxeb195511809cd1ef
        secret: 6b61c4f5ea6c1759d45b28d8ea2859c6
        msgDataFormat: JSON
